{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "some-project-web.fullname" . }}
  labels:
    {{- include "some-project-web.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: internal
    prometheus.io/path: /metrics
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: public
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.publicPort }}
    - name: internal
      protocol: TCP
      port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.internalPort }}
  selector:
    {{- include "some-project-web.selectorLabels" . | nindent 4 }}
  {{- end }}
